In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3],
              [4, 5, 6]])

In [8]:
arr.ndim

2

In [9]:
arr.shape

(2, 3)

In [11]:
c = np.zeros((3, 4))

In [12]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
d = np.zeros((3, 4))

In [14]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
e = np.eye(4)

In [19]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [22]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])